spring:
    dubbo:
        protocol:
            port: 20881 # 通信端口；在同一台机器上，这个端口号不能与其他服务提供者的端口号有重复的；你也可以不配置，dubbo会默认给你分配；
            name: rmi #协议
        application:
            name: cast-share-web  # dubbo应用名称
        registry:
            address: zookeeper://45.122.138.144:2192 # zookeeper注册中心地址
            timeout: 30000 # 接口调用超时时间，默认50000
            check: false # 项目启动时，检查注册中心是否可用（是否启动了zookeeper注册中心）
        provider:  # 重试次数，0表示不重试
            retries: 0
        service:
            group: cast1
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: 45.122.138.39
        port: 7002
        password:       # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
